### ISSUE TITLE
Code rearranging with Alt + Shift + F

### ISSUE THREAD

**Issue by ivanbuhov** [tsvetan-ganev/nativescript-vscode-snippets#5]
Code rearranging with `Alt + Shift + F` causes some platform specific properties to change their names.
https://groups.google.com/forum/#!topic/nativescript/6EK0Yf-5x_8

**Comment by tsvetan-ganev** [comment]
I cannot reproduce this using the latest version of VS Code in Windows. The ```Format Code``` option does not seem to work for ```.xml``` files at all, which is strange, because I'm sure it used to in previous versions. As for the problem - I remember something like this happening to me, but it's the way VS Code "beautifies" ```.xml```.
